# -*- coding: utf-8 -*-
"""Sports_Sentiment_Analysis_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kTe8sjM4WKLFHzNouQum_YFy6UBGYeBm
"""

!pip install nltk matplotlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from nltk.sentiment import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')

# Football Headlines
football_headlines = np.array([
    "Ronaldo scores brilliant goal in Champions League",
    "Barcelona suffers a shocking defeat in derby match",
    "Liverpool fans celebrate emotional comeback victory",
    "Manchester United faces tough loss against Chelsea",
    "Real Madrid claims top spot after dominant performance"
])

# Cricket Headlines
cricket_headlines = np.array([
    "India wins thrilling match against Australia",
    "Pakistan suffers narrow defeat in Asia Cup",
    "England dominates with outstanding batting performance",
    "New Zealand clinches victory in last over thriller",
    "Sri Lanka faces tough loss despite strong bowling attack"
])

sports = np.array(["football"] * len(football_headlines) + ["cricket"] * len(cricket_headlines))
headlines = np.concatenate((football_headlines, cricket_headlines))

df = pd.DataFrame({
    "sport": sports,
    "headline": headlines
})

df

sia = SentimentIntensityAnalyzer()
df["sentiment"] = df["headline"].apply(lambda x: sia.polarity_scores(x)["compound"])
df

grouped = df.groupby("sport")["sentiment"].mean()

plt.bar(grouped.index, grouped.values)
plt.xlabel("Sport")
plt.ylabel("Average Sentiment Score")
plt.title("Football vs Cricket: Sentiment Comparison")
plt.show()